name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:"Welcome"
    runs-on: ubuntu-latest
    permissions:"what_is_your_age
      <age> 
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
